project:
  type: website
  render:
    - slides
    - workshop
    - "*.qmd"

website:
  #announcement: 
  #  icon: info-circle
  #  dismissable: true
  #  content: "This tutorials site is still a work in progress. Thanks to those who are checking it out early!"
  #  type: danger
  #  position: below-navbar
  title: "SciPy 2026: Shiny Dashboards"
  google-analytics: "G-XFPBQ3BZ6M"
  favicon: img/favicon.ico
  navbar:
    logo: img/conf-logo.png
    left:
      - href: index.qmd
        text: Home
      - href: exercises.qmd
        text: Exercises
      - href: setup.qmd
        text: Setup
      - href: cloud.qmd
        text: Cloud
      - href: resources.qmd
        text: Resources
    right:
      - href: about.qmd
        text: About
      - icon: github
        href: https://github.com/chendaniely/scipy-2026-shiny

  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "👩🏻‍💻 Workshop Materials"
      - text: "Welcome + Introduction"
        href: workshop/01-welcome.qmd
      - text: "Basic building blocks"
        href: workshop/02-building_blocks.qmd
      - text: "Your first application"
        href: workshop/03-first_app.qmd
      - text: "Shiny reactivity"
        href: workshop/04-reactivity.qmd
      - text: "A more complex application"
        href: workshop/05-complex_app.qmd
      - text: "Introduction to Shiny modules"
        href: workshop/06-modules_intro.qmd
      - text: "Refactor your app into a module"
        href: workshop/07-modules_refactor.qmd
      - text: "Reuse your Shiny module"
        href: workshop/08-modules_compose.qmd
      - text: "Testing"
        href: workshop/09-testing.qmd
      - text: "Deploying your application"
        href: workshop/10-deploy.qmd
      - text: "Wrap up"
        href: workshop/11-wrap_up.qmd
      - text: "🎁 Bonus"
      - text: "An AI + LLM primer"
        href: workshop/90-ai_primer.qmd
      - text: "AI + LLM dashboards"
        href: workshop/91-ai_dashboards.qmd

format:
  html:
    theme:
      - flatly
      - brand
    css: styles.css
    highlight-style: github-light
    toc: true
    anchor-sections: true


custom-callout:
  exercise:
    title: "Exercise"
    icon: true
    icon-symbol: "🏋️"
    color: "#F97316"

filters:
  - shinylive
  - custom-callout
  - include-code-files
